# pr: none

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo hello from Linux

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: ci/osx-x64.sh
  - task: PublishPipelineArtifact
    inputs:
      artifactName: 'llvm-osx-x64'
      targetPath: 'osx-x64/lib'

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo hello from Windows

- job: Package
  pool:
    vmImage: 'vs2017-win2016'
  dependsOn:
  - Linux
  - macOS
  - Windows
  steps:
  - task: DownloadPipelineArtifact
    inputs:
      artifactName: 'llvm-osx-x64'
      targetPath: $(System.DefaultWorkingDirectory)/osx-x64
  - script: ls